apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: redis
spec:
  interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: redis
      version: 18.1.5
      sourceRef:
        kind: HelmRepository
        name: redis
  # https://github.com/bitnami/charts/blob/main/bitnami/redis/values.yaml
  values:
    auth:
      password: ${redis_password}
    master:
      persistence:
        enabled: ${redis_persistence_enabled:=false}
      resources:
        requests:
          cpu: ${redis_master_cpu_request:=100m}
          memory: ${redis_master_memory_request:=128Mi}
        limits:
          cpu: ${redis_master_cpu_limit:=200m}
          memory: ${redis_master_memory_limit:=256Mi}
    replica:
      persistence:
        enabled: ${redis_persistence_enabled:=false}
      replicaCount: ${redis_replica_count:=1}
