apiVersion: v1
kind: Secret
metadata:
    name: ghcr-auth
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:vllkwWTSzwI2SLa2o17RK4oe66aBRzdiVpiYoNN2ZNvj/cSEasS/fhf0a/lRXCcBC69J44WPnomX1KmHAtPmy7hWRJbjW5zH9w7AmVXWNHr0s4Yj2lZiE1CR7nBvhucWqwMpa6z18+To7ifAKY51d5Th0KED/DYBUB4zqiPijGze3HnMRO7JNyxsf2/vmyid6cDm7y6AztmxnxRBu0xK32ST+Cnh1sN8B80rD8AxCi6iSfvHd+cBD3I9yBIPz1ZdT8i1LTollT/V+e0vPMRGSmF4I84YnAP0PzQnNEzZqYAA48GU0WHzTlQjFgw29QTgcoZhs9W5innJiv6lmoqoJ4GTVhUTuRFF,iv:/qXilwtPqMv/z6UgwPAePhYP7VBXDjkLNaJSZnNZU94=,tag:gd3yHmSBm3BW/sR1fHvefw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age120p4hfdjg4x84rcl50vaus77l6rvpqyfjw23lszcpa089asr4s4qrtytwd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLL0RaMGp1VkxPeU5Sek5D
            MWtKYTdvNTBnMnIzSTRZNmpKbHFLSnBQbEFzCklGZCtVQ1lPZE5pNzhSS2NCOVM0
            cEZJdi9icHhvQjc5ajNQTHFPbnYzUWcKLS0tIGFJV0cza3YwY3o2bHBXTnIzN0p2
            V0J2U3FsTHp6VmFSdGUvQnNpd3pQcmsKmbutkJ0Qo8Jlu6ynJKD5l1Ce7zcRAEci
            k11NxWt6jG9r3tWaOcq0u5j3wVj0HZkvmC0IokkcTby4sMsRqyeNpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-19T11:38:48Z"
    mac: ENC[AES256_GCM,data:P/iLg+RLog7rVOdFzwnkJXtvMKbybqziG/jBeH2FQt+O/+c9Ybm6APWmah+5bBrmPz0nahCp6VEfEgwhdABTnH4IaDP9vO1TIadQrUdGwW1cHuwgAxYKmXtfJmkdtFdWL9/+s7YfVdL9wQo3qtC6prMozj3LwOhliptbJIXm2Uk=,iv:PSueoYTNhONGCYceb6bDeF5jgRVWICecpDG3xBAXMEo=,tag:x1vOrQTdV5aNqr4S4w6FbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
