apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set
spec:
  interval: 5m
  dependsOn:
    - name: gha-runner-scale-set-controller
      namespace: gha-runner-scale-set-controller
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.7.0
      sourceRef:
        kind: HelmRepository
        name: gha-runner-scale-set
  # https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/values.yaml
  values:
    githubConfigUrl: ${github_config_url}
    githubConfigSecret: github-token
    runnerScaleSetName: gha-runner-${cluster_domain}
    # Inspired by https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/deploying-runner-scale-sets-with-actions-runner-controller#using-docker-in-docker-or-kubernetes-mode-for-containers
    template:
      spec:
        initContainers:
          - name: init-dind-externals
            image: ${actions_runner_image}
            imagePullPolicy: Always
            command:
              [
                "cp",
                "-r",
                "-v",
                "/home/runner/externals/.",
                "/home/runner/tmpDir/",
              ]
            volumeMounts:
              - name: dind-externals
                mountPath: /home/runner/tmpDir
        containers:
          - name: runner
            image: ${actions_runner_image}
            imagePullPolicy: Always
            command: ["/home/runner/run.sh"]
            env:
              - name: DOCKER_HOST
                value: unix:///run/docker/docker.sock
            volumeMounts:
              - name: work
                mountPath: /home/runner/_work
              - name: dind-sock
                mountPath: /run/docker
                readOnly: true
          - name: dind
            image: docker:dind
            args:
              - dockerd
              - --host=unix:///run/docker/docker.sock
              - --group=$(DOCKER_GROUP_GID)
              - --dns=1.1.1.1
            env:
              - name: DOCKER_GROUP_GID
                value: "123"
            securityContext:
              privileged: true
            volumeMounts:
              - name: work
                mountPath: /home/runner/_work
              - name: dind-sock
                mountPath: /run/docker
              - name: dind-externals
                mountPath: /home/runner/externals
        volumes:
          - name: work
            emptyDir: {}
          - name: dind-sock
            emptyDir: {}
          - name: dind-externals
            emptyDir: {}
