apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../cert-manager/certificates/cluster-issuer-certificate.yaml
  - ../../../../cert-manager/cluster-issuers/selfsigned-cluster-issuer.yaml
  - ../../../../otel-operator/collectors/otel-collector-cluster.yaml
  - ../../../../otel-operator/collectors/otel-collector-node.yaml
  - ../../../../testkube/executors/dotnet-container-executor.yaml
