apiVersion: v1
kind: ConfigMap
metadata:
  name: variables
  namespace: flux-system
data:
  cluster_domain: oci-artifacts.ksail
  cluster_issuer_name: selfsigned-cluster-issuer
  pulumi_backend: file://
  pulumi_backend_path: /pulumi-backend
