apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 5m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  chart:
    spec:
      chart: traefik
      version: 26.1.0
      sourceRef:
        kind: HelmRepository
        name: traefik
  # https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
  values:
    image:
      tag: v3.0.0-beta3
    ports:
      web:
        redirectTo: websecure
      websecure:
        asDefault: true
    tlsStore:
      default:
        defaultCertificate:
          secretName: cluster-issuer-certificate-tls
    service:
      type: ${traefik_service_type:=LoadBalancer}
      spec:
        loadBalancerIP: ${traefik_ingress_load_balancer_ip}
    ingressRoute:
      dashboard:
        matchRule: Host(`traefik.${cluster_domain}`)
        entryPoints:
          - websecure
    resources:
      requests:
        cpu: ${traefik_cpu_request:=100m}
        memory: ${traefik_memory_request:=50Mi}
      limits:
        cpu: ${traefik_cpu_limit:=200m}
        memory: ${traefik_memory_limit:=100Mi}
