apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../cert-manager
  - ../../../../harbor
  - ../../../../pulumi-operator
  - ../../../../redis
  - ../../../../reloader
  - ../../../../testkube
  - ../../../../traefik
  - ../../../../gha-runner-scale-set
  - ../../../../gha-runner-scale-set-controller
  - ghcr-auth.sops.yaml

patches:
  - target:
      kind: HelmRelease
      name: gha-runner-scale-set
      namespace: gha-runner-scale-set
    path: gha-runner-scale-set-patch.yaml
