apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../cert-manager
  - ../../../../harbor
  - ../../../../pulumi-operator
  - ../../../../redis
  - ../../../../reloader
  - ../../../../testkube
  - ../../../../traefik
