apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../cert-manager
  - ../../../../gha-runner-scale-set
  - ../../../../gha-runner-scale-set-controller
  - ../../../../grafana
  - ../../../../harbor
  - ../../../../loki
  - ../../../../metrics-server
  - ../../../../mimir
  - ../../../../otel-collector-k8s
  - ../../../../otel-operator
  # Loki brings these in:
  # - ../../../../prometheus-operator-crds
  - ../../../../pulumi-operator
  - ../../../../redis
  - ../../../../reloader
  - ../../../../testkube
  - ../../../../traefik
  - ../../../../vertical-pod-autoscaler
  - ghcr-auth.sops.yaml

patches:
  - target:
      kind: HelmRelease
      name: gha-runner-scale-set
      namespace: gha-runner-scale-set
    path: gha-runner-scale-set-patch.yaml
  - target:
      kind: HelmRelease
      name: otel-collector-node
      namespace: otel-collector-k8s
    path: otel-collector-node-patch.yaml
  - target:
      kind: HelmRelease
      name: otel-collector-cluster
      namespace: otel-collector-k8s
    path: otel-collector-cluster-patch.yaml
