apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: testkube
spec:
  interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: testkube
      version: 1.16.52
      sourceRef:
        kind: HelmRepository
        name: testkube
  # https://github.com/kubeshop/helm-charts/blob/develop/charts/testkube/values.yaml
  values:
    testkube-api:
      uiIngress:
        enabled: true
        hosts:
          - testkube.${cluster_domain}
        path: /v1 # This is required for the ingress to work per https://github.com/kubeshop/helm-charts/issues/428#issuecomment-1873973628
    testkube-dashboard:
      ingress:
        enabled: true
        hosts:
          - testkube.${cluster_domain}
      apiServerEndpoint: testkube.${cluster_domain}${cluster_ingress_port:=}
