apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: testkube
spec:
  interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: testkube
      version: 1.16.17
      sourceRef:
        kind: HelmRepository
        name: testkube
  # https://github.com/kubeshop/helm-charts/blob/develop/charts/testkube/values.yaml
  values:
    testkube-api:
      uiIngress:
        enabled: true
        hosts:
          - testkube.${cluster_domain}
        path: /v1 # This is required for the ingress to work per https://github.com/kubeshop/helm-charts/issues/428#issuecomment-1873973628
      minio:
        resources:
          requests:
            cpu: ${testkube_minio_cpu_request:=50m}
            memory: ${testkube_minio_memory_request:=50Mi}
          limits:
            cpu: ${testkube_minio_cpu_limit:=100m}
            memory: ${testkube_minio_memory_limit:=150Mi}
      resources:
        requests:
          cpu: ${testkube_api_cpu_request:=200m}
          memory: ${testkube_api_memory_request:=200Mi}
        limits:
          cpu: ${testkube_api_cpu_limit:=200m}
          memory: ${testkube_api_memory_limit:=200Mi}
    testkube-dashboard:
      ingress:
        enabled: true
        hosts:
          - testkube.${cluster_domain}
      apiServerEndpoint: testkube.${cluster_domain}${cluster_ingress_port:=}
      resources:
        requests:
          cpu: ${testkube_dashboard_cpu_request:=25m}
          memory: ${testkube_dashboard_memory_request:=25Mi}
        limits:
          cpu: ${testkube_dashboard_cpu_limit:=50m}
          memory: ${testkube_dashboard_memory_limit:=50Mi}
    testkube-operator:
      proxy:
        resources:
          requests:
            cpu: ${testkube_operator_proxy_cpu_request:=25m}
            memory: ${testkube_operator_proxy_memory_request:=25Mi}
          limits:
            cpu: ${testkube_operator_proxy_cpu_limit:=50m}
            memory: ${testkube_operator_proxy_memory_limit:=50Mi}
      resources:
        requests:
          cpu: ${testkube_operator_cpu_request:=50m}
          memory: ${testkube_operator_memory_request:=50Mi}
        limits:
          cpu: ${testkube_operator_cpu_limit:=100m}
          memory: ${testkube_operator_memory_limit:=100Mi}
    mongodb:
      resources:
        requests:
          cpu: ${testkube_mongodb_cpu_request:=150m}
          memory: ${testkube_mongodb_memory_request:=100Mi}
